env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - GOFLAGS=-mod=vendor
  - GOPROXY=off
builds:
  - main: ./cmd/mustache
    binary: mustache
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64